route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
#  receiver: 'web.hook'
  receiver: 'telepush'
receivers:
#  - name: 'web.hook'
#    webhook_configs:
#      - url: 'http://127.0.0.1:5001/'
  - name: 'telepush'
    webhook_configs: 
      - url: 'https://telepush.dev/api/inlets/alertmanager/4bb83f'
#    http_config:
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
